[package]
name = "bus-factor"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.44"
octocrab = "0.13.0"
structopt = "0.3.25"
tokio = { version = "1.6.1", default-features = false, features = ["macros", "rt-multi-thread", "time"] }
